# Generated by Django 3.0 on 2020-05-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField(max_length=10000)),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problems.InputFile')),
                ('output_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problems.OutputFile')),
            ],
        ),
        migrations.AddField(
            model_name='inputfile',
            name='output_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Problems.OutputFile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='problems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Problems.Problem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='submissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Problems.Submission'),
        ),
    ]
