# Generated by Django 3.0 on 2020-05-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0002_auto_20200526_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_name',
            field=models.TextField(default='NONE', max_length=50),
        ),
    ]
