# Generated by Django 3.0 on 2020-05-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0003_problem_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Problems.Submission'),
        ),
    ]
