# Generated by Django 3.0 on 2020-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0006_auto_20200527_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.TextField(default='Unchecked', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.TextField(default='0.0000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FileField(upload_to='submissions'),
        ),
    ]
