# Generated by Django 3.0 on 2020-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0008_submission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.TextField(default='Unchecked', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TextField(default='0.0000000', max_length=20, null=True),
        ),
    ]
