# Generated by Django 3.0 on 2020-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0009_auto_20200527_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
