# Generated by Django 3.0 on 2020-05-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0010_auto_20200527_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_info',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256000),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_info',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0),
        ),
    ]
