# Generated by Django 3.0 on 2020-05-29 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Problems', '0013_blogs_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='likes',
        ),
        migrations.AddField(
            model_name='blogs',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
