# Generated by Django 3.0 on 2020-05-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0014_auto_20200529_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='likes',
            field=models.ManyToManyField(related_name='likers', to='Problems.Profile'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='Problems.Profile'),
        ),
    ]
