# Generated by Django 3.0 on 2020-05-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0016_blogs_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfile',
            name='file_content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
