# Generated by Django 3.0 on 2020-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0018_auto_20200530_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(default='...', max_length=100),
        ),
    ]
